# Generated by Django 5.2.15 on 2026-08-09 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0002_mealplan_start_day_alter_mealplan_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MealPlanTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mealplan',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='meal_plans', to='meal_plans.mealplantag'),
        ),
        migrations.AddConstraint(
            model_name='mealplantag',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_meal_plan_tag'),
        ),
    ]
