# Generated by Django 5.2.15 on 2026-08-10 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0003_mealplan_is_favorite_alter_mealplan_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mealplantag',
            name='unique_user_meal_plan_tag',
        ),
        migrations.AddConstraint(
            model_name='mealplantag',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_mealplantag_tag'),
        ),
    ]
