# Generated by Django 5.2.15 on 2026-08-10 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal_plans", "0004_remove_mealplantag_unique_user_meal_plan_tag_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mealplan",
            options={},
        ),
        migrations.AlterField(
            model_name="mealplan",
            name="start_day",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                default=0,
                help_text="Weekday number on which the meal plan starts (Monday=0)",
                validators=[django.core.validators.MaxValueValidator(6)],
            ),
        ),
    ]
