# Generated by Django 5.2.15 on 2026-08-14 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal_plans", "0007_plannedmealentry_remove_mealplanrecipe_meal_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="mealplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user",),
                name="unique_active_meal_plan_per_user",
            ),
        ),
    ]
