# Generated by Django 5.2.15 on 2026-08-20 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0005_remove_foodtag_unique_user_food_tag_and_more"),
        ("meal_plans", "0008_mealplan_is_active_and_more"),
        ("recipes", "0004_remove_recipetag_unique_user_recipe_tag_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RandomizerCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="randomizer_candidates",
                        to="foods.food",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="randomizer_candidates",
                        to="recipes.recipe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RandomizerItem",
            fields=[
                (
                    "plannedmealentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="meal_plans.plannedmealentry",
                    ),
                ),
                ("seed", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "candidates",
                    models.ManyToManyField(
                        blank=True,
                        related_name="randomizer_items",
                        to="meal_plans.randomizercandidate",
                    ),
                ),
            ],
            bases=("meal_plans.plannedmealentry",),
        ),
        migrations.AddConstraint(
            model_name="randomizercandidate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("food__isnull", False), ("recipe__isnull", True)),
                    models.Q(("food__isnull", True), ("recipe__isnull", False)),
                    _connector="OR",
                ),
                name="randomizer_candidate_exactly_one_item",
            ),
        ),
    ]
