# Generated by Django 5.2.15 on 2026-08-20 11:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0005_remove_foodtag_unique_user_food_tag_and_more"),
        ("meal_plans", "0009_randomizercandidate_randomizeritem_and_more"),
        ("recipes", "0004_remove_recipetag_unique_user_recipe_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="randomizercandidate",
            name="number_of_servings",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name="randomizercandidate",
            name="serving_size",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Only applicable when the item is a food.",
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="randomizercandidate",
            name="food",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="foods.food",
            ),
        ),
        migrations.AlterField(
            model_name="randomizercandidate",
            name="recipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="recipes.recipe",
            ),
        ),
    ]
