# Generated by Django 5.2.15 on 2026-08-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal_plans", "0010_randomizercandidate_number_of_servings_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="randomizeritem",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="randomizeritem",
            name="name",
            field=models.CharField(default="New randomizer", max_length=255),
            preserve_default=False,
        ),
    ]
