import difflib
import re
from pathlib import Path

from invoke import Context, task
from invoke.exceptions import Exit

from .utils import BASE_DIR, codebase_has_changes, info, print_success

# TODO this code should probably be moved to a separate package!

TASK_PATTERN = re.compile(
    r"""
^\s{2}
(?P<name>[a-zA-Z_][\w\.-]*)
(?:\s+\((?P<aliases>[^)]*)\))?
\s{2,}
""",
    re.VERBOSE,
)

MANUAL_HEADER = """
<!-- This document has been autogenerated with ./libreplate_cli.py dev.generate-manual -->

# LibrePlate CLI documentation

Display the help page:

```sh
./libreplate --help
```

To run a task:

```sh
./libreplate.py <task> <flags>
```

To learn more about a task:

```sh
./libreplate.py --help <task>
```
"""


@task(
    aliases=["gm"],
    help={
        "check": "Only check whether the generated manual differs from the existing file.",
    },
)
def generate_manual(c: Context, check: bool = False) -> None:
    """
    Generate a Markdown manual of all Invoke tasks.
    """

    if not c.config.cli.force.value and not codebase_has_changes(BASE_DIR / "tasks"):
        if c.config.cli.verbose.value:
            info("No changes in manual generation.")
        return

    output = Path(BASE_DIR / "docs/cli_manual.md")
    result = c.run(
        f"{BASE_DIR}/.venv/bin/python3 {BASE_DIR}/libreplate_cli.py --list", hide=True
    )
    tasks = []

    for line in result.stdout.splitlines():
        match = TASK_PATTERN.match(line)
        if not match:
            continue

        aliases = []
        if match.group("aliases"):
            aliases = [alias.strip() for alias in match.group("aliases").split(",")]

        tasks.append(
            {
                "name": match.group("name"),
                "aliases": aliases,
            }
        )

    markdown = [MANUAL_HEADER]

    markdown.append("## Available tasks\n")

    for task_data in tasks:
        name = task_data["name"]
        anchor = name.lower().replace(".", "-")
        markdown.append(f"- [`{name}`](#{anchor})")

    markdown.append("")

    for task_data in tasks:
        name = task_data["name"]
        aliases = task_data["aliases"]
        anchor = name.lower().replace(".", "-")

        help_text = c.run(
            f"{BASE_DIR}/.venv/bin/python3 {BASE_DIR}/libreplate_cli.py --help {name}",
            hide=True,
            warn=True,
        ).stdout.strip()

        # Remove the Options section when Invoke reports that there are no options.
        help_text = re.sub(
            r"\n\nOptions:\n\s*none\s*$",
            "",
            help_text,
        )

        markdown.append(f'<a id="{anchor}"></a>')
        markdown.append(f"\n## `{name}`\n")

        if aliases:
            markdown.append(f"**Aliases:** {', '.join(f'`{a}`' for a in aliases)}\n")

        markdown.extend(
            [
                "```text",
                help_text,
                "```",
            ]
        )

    generated = "\n".join(markdown)

    if check:
        if not output.exists():
            raise Exit(
                f"`{output}` does not exist. Run `./libreplate_cli.py dev.generate-manual`.",
                code=1,
            )

        existing = output.read_text(encoding="utf-8")

        if existing != generated:
            if c.config.cli.verbose:
                diff = difflib.unified_diff(
                    existing.splitlines(keepends=True),
                    generated.splitlines(keepends=True),
                    fromfile=str(output),
                    tofile="generated",
                )
                print("".join(diff))

            raise Exit(
                f"`{output}` is out of date. Run `./libreplate_cli.py dev.generate-manual`.",
                code=1,
            )

        print_success("Manual is up to date.")
        return

    output.write_text(generated, encoding="utf-8")
    print_success(f"Generated `{output}`")
