# Generated by Django 5.2.15 on 2026-08-02 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("body_metrics", "0001_initial"),
        ("nutrients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Graph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "graph_type",
                    models.CharField(
                        choices=[("line", "Line Graph"), ("bar", "Bar Graph")],
                        max_length=20,
                    ),
                ),
                (
                    "period_unit",
                    models.CharField(
                        choices=[
                            ("all", "All Data"),
                            ("day", "Day"),
                            ("week", "Week"),
                            ("month", "Month"),
                            ("year", "Year"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("period_amount", models.PositiveIntegerField(default=1)),
                (
                    "period_end_mode",
                    models.CharField(
                        choices=[
                            ("last_data_point", "Last Data Point"),
                            ("now", "Now"),
                            ("custom", "Custom"),
                        ],
                        default="last_data_point",
                        max_length=20,
                    ),
                ),
                (
                    "period_end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Only used when period_end_mode is CUSTOM.",
                        null=True,
                    ),
                ),
                (
                    "range_type",
                    models.CharField(
                        choices=[("fixed", "Fixed"), ("dynamic", "Dynamic")],
                        default="dynamic",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graphs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GraphLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "moving_average_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("day", "Day"),
                            ("week", "Week"),
                            ("month", "Month"),
                            ("year", "Year"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("moving_average_amount", models.PositiveIntegerField(default=1)),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="user_statistics.graph",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GraphLineBodyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "body_metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="body_metrics.bodymetric",
                    ),
                ),
                (
                    "graph_line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="body_metric",
                        to="user_statistics.graphline",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GraphLineNutrient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "graph_line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrient",
                        to="user_statistics.graphline",
                    ),
                ),
                (
                    "nutrient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nutrients.nutrient",
                    ),
                ),
            ],
        ),
    ]
