# Generated by Django 5.2.15 on 2026-08-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_statistics",
            "0002_alter_graph_options_alter_graphline_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="graph",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="graphline",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="graphlinebodymetric",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="graphlinenutrient",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
