# Generated by Django 5.2.15 on 2026-08-02 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BodyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("show_in_diary_total", models.BooleanField(default=True)),
                ("show_in_goal_edit", models.BooleanField(default=True)),
                ("is_single_entry", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="If True, this nutrient will be visible to users",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="body_metric",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nutrients",
            },
        ),
        migrations.CreateModel(
            name="BodyMetricLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.FloatField()),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "body_metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="body_metrics.bodymetric",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="body_metric_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="bodymetric",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", True)),
                fields=("name",),
                name="unique_global_body_metric_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="bodymetric",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "name"),
                name="unique_user_body_metric_name",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bodymetriclog",
            unique_together={("body_metric", "user", "date")},
        ),
    ]
