# Generated by Django 5.2.15 on 2026-08-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("body_metrics", "0003_add_body_metric_visibility"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bodymetric",
            options={"verbose_name": "Body Metrics"},
        ),
        migrations.RemoveField(
            model_name="bodymetric",
            name="show_in_diary_total",
        ),
        migrations.RemoveField(
            model_name="bodymetric",
            name="show_in_goal_edit",
        ),
        migrations.AlterField(
            model_name="bodymetric",
            name="is_single_entry",
            field=models.BooleanField(
                default=False, help_text="If only one log entry can be entered."
            ),
        ),
    ]
