# Generated by Django 5.2.15 on 2026-08-16 06:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("body_metrics", "0004_alter_bodymetric_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bodymetricsvisibility",
            old_name="show_in_diary",
            new_name="show_in_daily_log",
        ),
    ]
