# Generated by Django 5.2.15 on 2026-08-16 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "body_metrics",
            "0005_rename_show_in_diary_bodymetricsvisibility_show_in_daily_log",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bodymetric",
            name="is_single_entry",
        ),
    ]
