# Generated by Django 5.2.15 on 2026-08-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goalplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalbodymetric',
            name='goal_group',
        ),
    ]
