# Generated by Django 5.2.15 on 2026-08-02 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dark_mode", models.BooleanField(default=False)),
                (
                    "food_sort_mode",
                    models.CharField(
                        choices=[
                            ("name", "Name"),
                            ("-created_at", "Newest"),
                            ("created_at", "Oldest"),
                        ],
                        default="-created_at",
                        max_length=50,
                    ),
                ),
                ("theme_color", models.CharField(default="#0d6efd", max_length=7)),
                (
                    "recipe_sort",
                    models.CharField(
                        choices=[
                            ("last_used", "Last used"),
                            ("created", "Last created"),
                            ("updated", "Last updated"),
                            ("name", "Name"),
                        ],
                        default="last_used",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
