# Generated by Django 5.2.15 on 2026-08-10 08:05

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreferences",
            name="theme_color",
            field=colorfield.fields.ColorField(
                default="#107800", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
