# Generated by Django 5.2.15 on 2026-08-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nutrient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "abbreviation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Display unit for this nutrient's amount (e.g. g, mg, kcal).",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "show_in_diary_total",
                    models.BooleanField(
                        blank=True,
                        help_text="Show this nutrient in diary totals.",
                        null=True,
                    ),
                ),
                (
                    "show_in_diary_meal",
                    models.BooleanField(
                        blank=True,
                        help_text="Show this nutrient in individual diary meals.",
                        null=True,
                    ),
                ),
                (
                    "show_in_food_edit",
                    models.BooleanField(
                        blank=True,
                        help_text="Show this nutrient when editing a food.",
                        null=True,
                    ),
                ),
                (
                    "show_in_recipe",
                    models.BooleanField(
                        blank=True, help_text="Show this nutrient a recipe.", null=True
                    ),
                ),
                (
                    "show_in_recipes",
                    models.BooleanField(
                        blank=True,
                        help_text="Show this nutrient in recipes.",
                        null=True,
                    ),
                ),
                (
                    "show_in_foods",
                    models.BooleanField(
                        blank=True,
                        help_text="Show this nutrient in food detail/list pages.",
                        null=True,
                    ),
                ),
                ("show_in_goal_edit", models.BooleanField(blank=True, null=True)),
                (
                    "usda_nutrient_number",
                    models.IntegerField(
                        blank=True,
                        help_text="USDA nutrient number (e.g. 1003 for Protein).",
                        null=True,
                        unique=True,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Nutrients",
                "ordering": ["order"],
            },
        ),
    ]
