# Generated by Django 5.2.15 on 2026-08-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nutrients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nutrient",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="nutrient",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
