# Generated by Django 5.2.15 on 2026-08-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="USDAAPISettings",
            fields=[
                (
                    "key",
                    models.CharField(
                        max_length=64, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
        ),
    ]
