# Generated by Django 5.2.15 on 2026-08-11 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meal",
            options={},
        ),
    ]
