# Generated by Django 5.2.15 on 2026-08-02 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("nutrients", "0001_initial"),
        ("units", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("serving", models.FloatField()),
                ("barcode", models.CharField(blank=True, max_length=50, null=True)),
                ("brand", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                (
                    "usda_fdc_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="units.unit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Foods",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FoodNutrient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_nutrients",
                        to="foods.food",
                    ),
                ),
                (
                    "nutrient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nutrients.nutrient",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(
                fields=["barcode"], name="foods_food_barcode_a0aca0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(
                fields=["user", "brand"], name="foods_food_user_id_d68bec_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="foodnutrient",
            unique_together={("food", "nutrient")},
        ),
    ]
