# Generated by Django 5.2.15 on 2026-08-09 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_remove_food_usda_fdc_id_food_external_id_and_more'),
        ('nutrients', '0002_alter_nutrient_description_alter_nutrient_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodtag',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='foodnutrient',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='foodtag',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='foodtag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foodtag',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='foodtag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='foodnutrient',
            constraint=models.UniqueConstraint(fields=('food', 'nutrient'), name='unique_food_nutrient'),
        ),
    ]
