name: Verify

on:
  push:
    branches: [master]
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: libreplate
          POSTGRES_PASSWORD: unsafe_development_pwd!1
          POSTGRES_DB: libreplate_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U libreplate -d libreplate_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache virtual environment
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Sync dependencies
        run: uv sync

      - name: Create environment file
        run: |
          cp .env_example .env
          sed -i "s|^FRONTEND_DIST=.*|FRONTEND_DIST=${{ github.workspace }}/frontend/dist/|" .env
          sed -i "s|^SECRET_KEY=.*|SECRET_KEY=github-insecure-ci-key|" .env
          sed -i "s|^SESSION_COOKIE_SECURE=.*|SESSION_COOKIE_SECURE=False|" .env
          sed -i "s|^CSRF_COOKIE_SECURE=.*|CSRF_COOKIE_SECURE=False|" .env

      - name: Init LibrePlate
        run: uv run python libreplate_cli.py deploy.init

      - name: Run verification
        run: uv run python libreplate_cli.py --verbose dev.verify

      - name: Build front end
        run: uv run python libreplate_cli.py deploy.build-front-end

      - name: Upload frontend build
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist/


  release-nightly:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: verify

    runs-on: ubuntu-latest

    permissions:
      contents: write

    # TODO front end does not have to be build if there are no changes
    steps:
      - name: Download frontend build
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: frontend-dist

      - name: Create zip
        run: |
          cd frontend-dist
          zip -r ../frontend-dist.zip .

      - name: Publish nightly release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          target_commitish: ${{ github.sha }}
          name: Nightly
          prerelease: true
          make_latest: false
          generate_release_notes: false
          files: frontend-dist.zip